/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_janino_ndkfilecrypt_Cryptor */

#ifndef _Included_com_janino_ndkfilecrypt_Cryptor
#define _Included_com_janino_ndkfilecrypt_Cryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_janino_ndkfilecrypt_Cryptor
 * Method:    crypt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_janino_ndkfilecrypt_Cryptor_crypt
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_janino_ndkfilecrypt_Cryptor
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_janino_ndkfilecrypt_Cryptor_decrypt
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
